name: Create a new release
on:
  release:
    types: [published]
jobs:
  tag:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          composer install --no-dev --optimize-autoloader
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: zip -X -r build/taiwan-payments-for-wc-block.zip . -x *.git* node_modules/\* .* "*/\.*" *.dist grumphp.yml composer.* build**
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: taiwan-payments-for-wc-block
          path: build/taiwan-payments-for-wc-block.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/taiwan-payments-for-wc-block.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}